class UI_Config{
  // set the padding margin space
  static containerPadding = 20
  static containerMargin = 20
  static rowSpace = 10
  static columnSpace = 10


  // set the color
  static PrimaryColor = '#1a8af3'
  static SecondaryColor = '#ffc3c3c3'
  static SuccessColor = '#28a745'
  static DangerColor = '#dc3545'


  // set the font size
  static titleFontSize = 20
  static subTitleFontSize = 16
  static normalFontSize = 14
  static smallFontSize = 12


  // set the element size
  static buttonHeight = 30
  static navBarHeight = 50

  // set the border radius
  static buttonBorderRadius = 5
}

export {UI_Config}